---
title: "Marquis"
author: "Chloé Marquis"
format: 
  html: default
  pdf: default

---

Link to my github repository : https://github.com/chloemrq/grades-lab


```{r}
library(here)
here::i_am("Chloé Marquis.Rproj")
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
library(lubridate)
```
### Question 1
```{r}
courses <- vroom(here("courses.csv"))
```
### Question 2
```{r}
courses <- courses |>
rename(
  `course name` = course,
  identifier = course_id,
  trimester = trimester,
  `number of exams` = nb_grades
)

courses |>
  arrange(`course name`) |>
  knitr::kable()
```
### Question 3
```{r}
students <- vroom("students.csv",
                   col_types = vroom::cols(
                     id = vroom::col_integer(),
                     group = vroom::col_factor(),
                     birth_date = vroom::col_date(format = "%Y-%m-%d"),
                     sex = vroom::col_factor(levels = c("F", "M"))
                     )
)

# check 
sapply(students, class) # OK
```


### Question 4
```{r}
grades <- vroom(
  here("grades.csv"), 
  delim = ":",
  na = "unknown")
```
### Question 5
```{r}
students |>
  count(group) |>              
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(
    title = "Number of students per group",
    x = "Group",
    y = "Number of students"
)
```

### Question 6
```{r}
students |>
  count(group, sex) |>              
  ggplot(aes(x = group, y = n, fill= sex)) +
  geom_col() +
  labs(
    title = "Number of students per group",
    x = "Group",
    y = "Number of students",
    fill = "Sex"
)
```

### Question 7
```{r}
students |>
  mutate(age = time_length(today() - birth_date, unit = "year")) |>
    ggplot(aes(x = age)) +
    geom_histogram(binwidth=1) +       
    labs(
      title = "Age distribution",
      x = "Age",
      y = "Number of students"
    )
```

### Question 8
```{r}

# adding an age column
students <- students |>
  mutate(age = round(time_length(today() - birth_date, unit = "year")))

students |>
  group_by(group) |>
  summarise(
    median_age = round(median(age, na.rm = TRUE))) |>
  arrange(group) |>
  knitr::kable()
```


### Question 9
```{r}
students |>
  group_by(group) |>
  slice_max(age, n=1, with_ties = FALSE) |>
  select(id, sex, age) |>
  arrange(desc(age)) |>
  knitr::kable()
```

### Question 10
```{r}
num_grades <- sum(!is.na(grades$grade))
```
The data set contains `r num_grades` grades.

### Question 11
```{r}
# first merge the grades and students dataset to have grades and group in the same data set 
grades_with_group <- grades |>
  left_join(students, by = "id")

avg_bio <- grades_with_group |>
  filter(course_id == 3) |>  # code for this course is 3 (from the courses data set)
  group_by(group) |>
  summarise(
    avg_grade = mean(grade, na.rm = TRUE)  
  )

ggplot(avg_bio, aes(x = factor(group), y = avg_grade)) +
  geom_col() +  
  labs(
    title = "Average grade in Bioengineering and Genetic Modification",
    x = "Group",
    y = "Average grade"
  )
```
### Question 12
```{r}
# need to join courses and grades to get the grades per trimester 
grades_per_trimester <- grades |>
  left_join(courses |> select(identifier, trimester), 
            by = c("course_id" = "identifier"))


ggplot(grades_per_trimester, aes(x = grade, color = factor(trimester), fill = factor(trimester))) +
  geom_density(alpha=0.3) +
  labs(
    title = "Density plot of grades per trimester",
    x = "Grade",
    y = "Density",
    color = "Trimester",
    fill = "Trimester"
  )
```
### Question 13
```{r}
grades_per_student <- grades |>
  group_by(id) |>
  summarise(num_grades = sum(!is.na(grade))) |>  
  left_join(students |> select(id, group, sex), by = "id") |>
  select(id, group, sex, num_grades) |>
  arrange(id) 

grades_per_student |>
  slice_head(n = 5) |>     
  knitr::kable()

grades_per_student |>
  summarise(
    minimum = min(num_grades),
    maximum = max(num_grades),
    average = round(mean(num_grades), 2),
    median = median(num_grades)) |> 
  knitr::kable()
```

### Question 14
```{r}
grades_per_student |> 
  ggplot(aes(x = sex, y = num_grades, fill = sex)) +
  geom_boxplot() +
  labs(
    title = "Distribution of number of Grades by sex",
    x = "Sex",
    y = "Number of grades"
  )
```
### Question 15
```{r}
grades_with_group <- grades_with_group |>
  left_join(
    grades_per_student |> select(id, num_grades),
    by = "id"
  )

corp_espionage_ds <- grades_with_group |>
  filter(course_id == 9) |>      
  group_by(id, group, sex) |>
  summarise(num_grades = n(), .groups = "drop") |>
  arrange(id)

corp_espionage_ds |>
  slice_head(n = 5) |>      
  knitr::kable()
```

### Question 16
```{r}
corp_espionage_ds |>
  count(num_grades) |>  
  arrange(num_grades) |>
  ggplot(aes(x = factor(num_grades), y = n)) +
  geom_col() +   
  labs(
    title = "Distribution of Number of Grades per Student in Corporate Espionage and Industrial Sabotage",
    x = "Number of Grades",
    y = "Number of Students"
  )
```
### Question 17
```{r}
ggplot(corp_espionage_ds, aes(x = factor(group), y = num_grades)) +
  geom_boxplot() +
  labs(
    title = "Number of grades per student by Group Corporate Espionage and Industrial Sabotage",
    x = "Group",
    y = "Number of grades"
  )
```
### Question 18
